version: '3'
services:
  kafka:
    image: lensesio/fast-data-dev:latest
    container_name: kafka
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"
      - "9092:9092"
    environment:
      - ADV_HOST=localhost
